version: "3.7"
services:
  mongo:
    image: mongo:3.6.14
    volumes:
      - db-data:/data/db
    networks:
      - covid19-network

  covid19:
    build: .
    environment:
      SERVICE_HOST: "covid19"
      SERVICE_PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017/covid19"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./package.json:/app/package.json
      - ./src:/app/src
    networks:
      - covid19-network

networks:
  covid19-network:

volumes:
  db-data:
